server:
  port: 8761

spring:
  application:
    name: eureka-service

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'


eureka:
  instance:
    hostname: eureka-service

  client:
    serviceUrl:
      defaultZone: http://eureka-service:${server.port}/eureka
    register-with-eureka: true
    fetch-registry: true

