app-config:
  port: 8999
  localstack-address: http://localstack:4566
  postgres-address: postgres-storage:5432

server:
  port: ${app-config.port}

spring:
  application:
    name: storage-service

  #Postgresql Connection settings
  datasource:
    url: jdbc:postgresql://${app-config.postgres-address}/storages
    username: test
    password: password

  #JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL10Dialect

  # Multipart config
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

amazonProperties:
  accessKey: test
  secretKey: test
  url: ${app-config.localstack-address}


